### ISSUE TITLE
استفاده از ابزار ویراستار

### ISSUE THREAD

**Issue by NabiKAZ** [mehdisadeghi/khayyam#1]
با سلام،

کارتون بسیار ارزشمند بود. هم از نظر فنی هم ادبی!
از نظر دستوری خوب نوشتید و تقریباً مشکلی نیست اما با این حال، پیشنهاد می‌کنم با این ابزار: https://virastyar.com/virastlive/index.html محصول شورای عالی انقلاب فرهنگی، متون رو یک بررسی کنید احتمالاً بعضی جاها میتونه بهتر به شه.

کامنتهای توی سایتتون مشکل داشت ناچاراً اینجا پیام دادم.

باتشکر

**Comment by mehdisadeghi** [comment]
@NabiKAZ خیلی ممنونم.

حتما این ابزار رو نگاه می‌کنم. البته تعدادی خطای تایپی داشتم که بعضی‌ها رو درست کردم. ولی من شعرها رو از روی کتاب جیبی کوچکی که همراه داشتم پیاده کردم در حالی که می‌دونم خیلی از ابیات نسخه‌های مختلفی ازشون موجوده. بعضی جاها که شک داشتم از اینترنت بویژه سایت گنجور استفاده کردم.

کامنت‌دونی سایت رو هم درست می‌کنم :)

**Comment by mehdisadeghi** [comment]
من این ایشو رو می‌بندم، اگر مشکلی بود بازش بکنید.
